image: alpine/edge
packages:
  - "docker"
  - "git"
  - "bash"
  - "shadow"
sources:
  - "https://git.sr.ht/~dieff/dockerfiles"
secrets:
  - "a270ed90-5fe7-4bac-9d11-c3f479e2bfc7" # github ssh key
  - "1f082fda-00c7-443a-906c-effcb0c66b8c" # docker creds
tasks:
  - mirrir_to_gh: |
      cd dockerfiles
      git checkout master
      echo -e "Host *\n    StrictHostKeyChecking no" >> ~/.ssh/config
      git remote add github git@github.com:Dieff/dockerfiles.git
      git push github
  - docker_setup: |
      sudo mount -t tmpfs -o size=4G /dev/null /dev/shm
      sudo service cgroups start
      sleep 2
      sudo nohup dockerd --bip 172.18.0.1/16 </dev/null >/dev/null 2>&1 &
      sleep 5
      sudo usermod -aG docker $(whoami)
  - build_and_deploy_docker: |
      cd dockerfiles
      ./publish.sh
