image: alpine/edge
packages:
  - "docker"
  - "git"
  - "bash"
sources:
  - "https://git.sr.ht/~dieff/dockerfiles"
secrets:
  - "a270ed90-5fe7-4bac-9d11-c3f479e2bfc7" # github ssh key
  - "1f082fda-00c7-443a-906c-effcb0c66b8c" # docker creds
tasks:
  - mirrir_to_gh: |
      cd dockerfiles
      git checkout master
      echo "github.com ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAq2A7hRGmdnm9tUDbO9IDSwBK6TbQa+PXYPCPy6rbTrTtw7PHkccKrpp0yVhp5HdEIcKr6pLlVDBfOLX9QUsyCOV0wzfjIJNlGEYsdlLJizHhbn2mUjvSAHQqZETYP81eFzLQNnPHt4EVVUh7VfDESU84KezmD5QlWpXLmvU31/yMf+Se8xhHTvKSCZIFImWwoG6mbUoWf9nzpIoaSjB+weqqUUmpaaasXVal72J+UX2B+2RPW3RcT0eOzQgqlJL3RKrTJvdsjE3JEAvGq3lGHSZXy28G3skua2SmVi/w4yCE6gbODqnTWlg7+wC604ydGXA8VJiS5ap43JXiUFFAaQ==" >> ~/.ssh/authorized_keys
      git remote add github git@github.com:Dieff/dockerfiles.git
      git push github
  - run_deploy: |
      service docker start
      cd dockerfiles
      bash publish.sh
